"""add timestamp column to the questions table

Revision ID: 2c82e887f8c9
Revises: 4f54e1e4d245
Create Date: 2018-09-22 19:27:40.671398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c82e887f8c9'
down_revision = '4f54e1e4d245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'timestamp')
    # ### end Alembic commands ###
