"""add has_answer field to the questions table

Revision ID: c0c368f0450d
Revises: ab4c971c48dc
Create Date: 2018-09-26 03:48:59.955470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c368f0450d'
down_revision = 'ab4c971c48dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('has_answer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'has_answer')
    # ### end Alembic commands ###
