"""add account_confirmed column to users table

Revision ID: dc111554ac17
Revises: 0ba51011e216
Create Date: 2018-09-04 15:22:24.501771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc111554ac17'
down_revision = '0ba51011e216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_confirmed')
    # ### end Alembic commands ###
